### ISSUE TITLE
Good

### ISSUE THREAD

**Issue by n0thels3** [Pix4Devs/CursedSpirits#1]
Good script, it brings back memories of ACDS Panel.

I have a question, what VPS do you use?

**Comment by Z3NTL3** [comment]
> Good script, it brings back memories of ACDS Panel.
> 
> I have a question, what VPS do you use?

https://github.com/Pix4Devs/CursedSpirits#power

**Comment by Z3NTL3** [comment]
@n0thels3 I would suggest you to update, we have added more functionalities.

See #2

**Comment by Z3NTL3** [comment]
@n0thels3 hi may i ask you to test and review https://github.com/Z3NTL3/Exterminator, Its a CLI tool that wraps and empowers CursedSpirits with some hot-reloads and amplifications.
